name: Build and Developmental Release

on:
  push:
    branches: 
      - '**'  # Trigger on any branch push
  workflow_dispatch:

jobs:
  build:
    name: Build x64-Release
    runs-on: windows-latest

    steps:
      # Checkout the code
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Build Frontend
        shell: pwsh
        run: |
          cd frontend
          npm install
          npm run build
          xcopy "out" "..\\backend\\bin\\resources\\adaf.starforge" /E /H /C /I /Y

      - uses: geode-sdk/build-geode-mod@main
        id: build
        with:
          path: backend 

      - name: Compress Build Output
        shell: pwsh
        run: |
          cd backend
          if (Test-Path out) { Remove-Item -Recurse -Force out }
          mkdir out
          xcopy bin\resources out\resources /E /I /Y
          xcopy resources out\resources /E /I /Y
          cp about.md out/
          cp changelog.md out/
          cp logo.png out/
          cp mod.json out/
          cp build/*.dll out/
          Remove-Item out\*.psd -Recurse -Force -ErrorAction SilentlyContinue
          Remove-Item out\*.blend -Recurse -Force -ErrorAction SilentlyContinue
          cd out
          7z a -tzip adaf.starforge.geode -mx9 *
         
      # Upload the compressed file
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: adaf.starforge.geode
          path: backend/out/adaf.starforge.geode

  release:
    name: Create Developmental Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Download the compressed build artifact
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: adaf.starforge.geode
          path: .

      # Create GitHub Release
      - name: Update Development Release
        uses: andelf/nightly-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: develop
          name: 'Developmental Build'
          body: |
            Development release for commit ${{ github.sha }}.
          files: |
            ./adaf.starforge.geode